name: SHM_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  geolocator: ^13.0.1
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.3.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/

  fonts:
    - family: DIN Next Arabic
      fonts:
        - asset: fonts/DINNextArabic-Regular.ttf
          weight: 400

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

  # خلفية بيضاء للأيقونة
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  android_adaptive_icon_background: "#FFFFFF"
  android_adaptive_icon_foreground: "assets/icon/app_icon.png"

  remove_alpha_ios: true
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#42A5F5"
